spring:
  profiles:
    active:
     - dev
---
spring:
  profiles: dev
  application:
    name: microservicetest-config-dev

config:
  info: configtest1
---
spring:
  profiles: test
  application:
    name: microservicetest-config-test
