spring:
  profiles:
    active:
     - dev
---
spring:
  profiles: dev
  application:
    name: microservicetest-config-dev
---
spring:
  profiles: test
  application:
    name: microservicetest-config-test