spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.221.130:3306/cloud_demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
